default_settings:
  trainer_type: ppo
  hyperparameters:
    batch_size: 2048
    buffer_size: 20480
    learning_rate: 3.0e-4
    beta: 5.0e-4
    epsilon: 0.2
    lambd: 0.99
    num_epoch: 2
    learning_rate_schedule: linear
  network_settings:
    normalize: false
    hidden_units: 128
    num_layers: 3
  reward_signals:
    extrinsic:
      gamma: 0.99
      strength: 1.0
  max_steps: 5000000
  time_horizon: 1000
  summary_freq: 20480

engine_settings:
  # width: 84
  # height: 84
  # quality_level: 5
  time_scale: 1000
  # target_frame_rate: -1
  # capture_frame_rate: 60
  no_graphics: true
